services:
  # Backend API
  - type: web
    name: selaiah-backend
    runtime: node
    region: oregon
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: MONGODB_URI
        value: mongodb+srv://Vercel-Admin-selaiah_admin:MKLmG6WWesIZUKIy@selaiah-admin.9ji561i.mongodb.net/selaiah?retryWrites=true&w=majority
      - key: SESSION_SECRET
        generateValue: true
      - key: JWT_SECRET
        generateValue: true
      - key: FRONTEND_URL
        value: https://selaiah-project.vercel.app
